import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import SideNav from "@/app/ui/sidenavi";
import { Children } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({children}: {children: React.ReactNode}){
    
    return(
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
            <div className = "w-full bg-slate-50 flex-none md:w-64">
              
              <SideNav />
            </div>
            <div className="flex-grow p-3 md:overflow-y-auto md:p-6 bg-slate-100">{children}</div>
        </div>
    )
}
